### PR TITLE
Created a custom 404 page for this repo

### PR DESCRIPTION
**Pull request by susantruong**
Created a 404 error page for this GitHub page site https://github.com/ywpark1/portfolio-generator/issues/22

### CODE REVIEW

**Comment by ywpark1** [comment]
Thanks @susantruong ,

Can you elaborate more about this PR?

**Comment by humphd** [comment]
@ywpark1 she's adding a static 404 page, so that if someone tries to open a URL on the gh-pages site that doesn't exist, you can give back a themed 404 that looks like the rest of your site vs. something generic.  After this lands, you can style this HTML to match your template.

**Comment by ywpark1** [comment]
Can we have this with separate directory under the template directory?

We can add this file when generating process fails and users will see this page after pushing to the repository.

**Comment by susantruong** [comment]
@ywpark1 I am not sure where you want to put the `404.html` file. Therefore, I have removed the `404.html` file. Also, I created a new `404page` folder that is including `404.html` file and `404.png` image and put it in 3 different following folders:

1. 404page/
2. Portfolio-generator-console/404page/
3. templates/404page/

May you check it? Thanks.

**Comment by ywpark1** [comment]
Thanks @susantruong 

I will merge it. Thanks.

**Pull request merged**
